#!/bin/bash

# Script de verificación del proyecto KAREH PRO

echo "🔍 Verificando estructura de KAREH PRO..."
echo ""

# Verificar archivos raíz
echo "✓ Archivos de configuración:"
[ -f "package.json" ] && echo "  ✅ package.json" || echo "  ❌ package.json"
[ -f "vite.config.js" ] && echo "  ✅ vite.config.js" || echo "  ❌ vite.config.js"
[ -f "tailwind.config.js" ] && echo "  ✅ tailwind.config.js" || echo "  ❌ tailwind.config.js"
[ -f "eslint.config.js" ] && echo "  ✅ eslint.config.js" || echo "  ❌ eslint.config.js"
[ -f "index.html" ] && echo "  ✅ index.html" || echo "  ❌ index.html"
[ -f "README.md" ] && echo "  ✅ README.md" || echo "  ❌ README.md"

echo ""
echo "✓ Carpetas principales:"
[ -d "src/components/ui" ] && echo "  ✅ src/components/ui" || echo "  ❌ src/components/ui"
[ -d "src/components/layout" ] && echo "  ✅ src/components/layout" || echo "  ❌ src/components/layout"
[ -d "src/components/dashboard" ] && echo "  ✅ src/components/dashboard" || echo "  ❌ src/components/dashboard"
[ -d "src/components/appointments" ] && echo "  ✅ src/components/appointments" || echo "  ❌ src/components/appointments"
[ -d "src/components/patients" ] && echo "  ✅ src/components/patients" || echo "  ❌ src/components/patients"
[ -d "src/context" ] && echo "  ✅ src/context" || echo "  ❌ src/context"
[ -d "src/hooks" ] && echo "  ✅ src/hooks" || echo "  ❌ src/hooks"
[ -d "src/services" ] && echo "  ✅ src/services" || echo "  ❌ src/services"
[ -d "src/lib" ] && echo "  ✅ src/lib" || echo "  ❌ src/lib"
[ -d "src/pages" ] && echo "  ✅ src/pages" || echo "  ❌ src/pages"

echo ""
echo "✓ Componentes UI:"
[ -f "src/components/ui/Button.jsx" ] && echo "  ✅ Button.jsx" || echo "  ❌ Button.jsx"
[ -f "src/components/ui/Card.jsx" ] && echo "  ✅ Card.jsx" || echo "  ❌ Card.jsx"
[ -f "src/components/ui/Badge.jsx" ] && echo "  ✅ Badge.jsx" || echo "  ❌ Badge.jsx"
[ -f "src/components/ui/Input.jsx" ] && echo "  ✅ Input.jsx" || echo "  ❌ Input.jsx"
[ -f "src/components/ui/KpiCard.jsx" ] && echo "  ✅ KpiCard.jsx" || echo "  ❌ KpiCard.jsx"
[ -f "src/components/ui/Modal.jsx" ] && echo "  ✅ Modal.jsx" || echo "  ❌ Modal.jsx"
[ -f "src/components/ui/Select.jsx" ] && echo "  ✅ Select.jsx" || echo "  ❌ Select.jsx"

echo ""
echo "✓ Layout:"
[ -f "src/components/layout/Sidebar.jsx" ] && echo "  ✅ Sidebar.jsx" || echo "  ❌ Sidebar.jsx"
[ -f "src/components/layout/PageContainer.jsx" ] && echo "  ✅ PageContainer.jsx" || echo "  ❌ PageContainer.jsx"
[ -f "src/components/layout/PageHeader.jsx" ] && echo "  ✅ PageHeader.jsx" || echo "  ❌ PageHeader.jsx"

echo ""
echo "✓ Dashboard:"
[ -f "src/components/dashboard/DashboardKpis.jsx" ] && echo "  ✅ DashboardKpis.jsx" || echo "  ❌ DashboardKpis.jsx"
[ -f "src/components/dashboard/DashboardCharts.jsx" ] && echo "  ✅ DashboardCharts.jsx" || echo "  ❌ DashboardCharts.jsx"
[ -f "src/components/dashboard/DashboardWidgets.jsx" ] && echo "  ✅ DashboardWidgets.jsx" || echo "  ❌ DashboardWidgets.jsx"

echo ""
echo "✓ Appointments:"
[ -f "src/components/appointments/AppointmentCard.jsx" ] && echo "  ✅ AppointmentCard.jsx" || echo "  ❌ AppointmentCard.jsx"
[ -f "src/components/appointments/TimeSlotsGrid.jsx" ] && echo "  ✅ TimeSlotsGrid.jsx" || echo "  ❌ TimeSlotsGrid.jsx"
[ -f "src/components/appointments/DailySchedule.jsx" ] && echo "  ✅ DailySchedule.jsx" || echo "  ❌ DailySchedule.jsx"
[ -f "src/components/appointments/AppointmentWizard.jsx" ] && echo "  ✅ AppointmentWizard.jsx" || echo "  ❌ AppointmentWizard.jsx"
[ -f "src/components/appointments/WizardStepPatient.jsx" ] && echo "  ✅ WizardStepPatient.jsx" || echo "  ❌ WizardStepPatient.jsx"
[ -f "src/components/appointments/WizardStepDoctor.jsx" ] && echo "  ✅ WizardStepDoctor.jsx" || echo "  ❌ WizardStepDoctor.jsx"
[ -f "src/components/appointments/WizardStepDateTime.jsx" ] && echo "  ✅ WizardStepDateTime.jsx" || echo "  ❌ WizardStepDateTime.jsx"
[ -f "src/components/appointments/WizardStepConfirmation.jsx" ] && echo "  ✅ WizardStepConfirmation.jsx" || echo "  ❌ WizardStepConfirmation.jsx"

echo ""
echo "✓ Patients:"
[ -f "src/components/patients/PatientsTable.jsx" ] && echo "  ✅ PatientsTable.jsx" || echo "  ❌ PatientsTable.jsx"
[ -f "src/components/patients/PatientsToolbar.jsx" ] && echo "  ✅ PatientsToolbar.jsx" || echo "  ❌ PatientsToolbar.jsx"
[ -f "src/components/patients/PatientForm.jsx" ] && echo "  ✅ PatientForm.jsx" || echo "  ❌ PatientForm.jsx"

echo ""
echo "✓ Contextos:"
[ -f "src/context/AuthContext.jsx" ] && echo "  ✅ AuthContext.jsx" || echo "  ❌ AuthContext.jsx"
[ -f "src/context/FeaturesContext.jsx" ] && echo "  ✅ FeaturesContext.jsx" || echo "  ❌ FeaturesContext.jsx"

echo ""
echo "✓ Hooks:"
[ -f "src/hooks/useAuth.js" ] && echo "  ✅ useAuth.js" || echo "  ❌ useAuth.js"
[ -f "src/hooks/useFeatures.js" ] && echo "  ✅ useFeatures.js" || echo "  ❌ useFeatures.js"
[ -f "src/hooks/useAppointments.js" ] && echo "  ✅ useAppointments.js" || echo "  ❌ useAppointments.js"
[ -f "src/hooks/usePatients.js" ] && echo "  ✅ usePatients.js" || echo "  ❌ usePatients.js"
[ -f "src/hooks/useStats.js" ] && echo "  ✅ useStats.js" || echo "  ❌ useStats.js"

echo ""
echo "✓ Servicios:"
[ -f "src/services/appointments.service.js" ] && echo "  ✅ appointments.service.js" || echo "  ❌ appointments.service.js"
[ -f "src/services/patients.service.js" ] && echo "  ✅ patients.service.js" || echo "  ❌ patients.service.js"
[ -f "src/services/stats.service.js" ] && echo "  ✅ stats.service.js" || echo "  ❌ stats.service.js"
[ -f "src/services/audit.service.js" ] && echo "  ✅ audit.service.js" || echo "  ❌ audit.service.js"

echo ""
echo "✓ Lib:"
[ -f "src/lib/constants.js" ] && echo "  ✅ constants.js" || echo "  ❌ constants.js"
[ -f "src/lib/utils.js" ] && echo "  ✅ utils.js" || echo "  ❌ utils.js"

echo ""
echo "✓ Páginas:"
[ -f "src/pages/DashboardPage.jsx" ] && echo "  ✅ DashboardPage.jsx" || echo "  ❌ DashboardPage.jsx"
[ -f "src/pages/AppointmentsPage.jsx" ] && echo "  ✅ AppointmentsPage.jsx" || echo "  ❌ AppointmentsPage.jsx"
[ -f "src/pages/PatientsPage.jsx" ] && echo "  ✅ PatientsPage.jsx" || echo "  ❌ PatientsPage.jsx"

echo ""
echo "✓ Archivos principales:"
[ -f "src/App.jsx" ] && echo "  ✅ App.jsx" || echo "  ❌ App.jsx"
[ -f "src/App.css" ] && echo "  ✅ App.css" || echo "  ❌ App.css"
[ -f "src/main.jsx" ] && echo "  ✅ main.jsx" || echo "  ❌ main.jsx"
[ -f "src/index.css" ] && echo "  ✅ index.css" || echo "  ❌ index.css"

echo ""
echo "════════════════════════════════════════════"
echo "🎉 Verificación completada"
echo "════════════════════════════════════════════"
echo ""
echo "Próximos pasos:"
echo "1. npm install"
echo "2. npm run dev"
echo "3. Abre http://localhost:5173"
echo ""
